branches:
  except:
    - gh-pages

install:
  - set PATH=C:\Python36;%PATH%
  - cmake --version

build_script:
  - mkdir build
  - cd build
  - cmake .. -DCLI_SINGLE_FILE_TESTS=ON -DCMAKE_GENERATOR="Visual Studio 14 2015"
  - cmake --build .

test_script:
    - ctest --output-on-failure
