version: 2.1.2.{build}

branches:
  only:
    - main
    - v1

install:
  - git submodule update --init --recursive
  - py -3 --version
  - set PATH=C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%
  - cmake --version
  - python --version
  - python -m pip --version
  - python -m pip install conan
  - conan user
  - conan --version

build_script:
  - mkdir build
  - cd build
  - ps: cmake .. -DCLI11_WARNINGS_AS_ERRORS=ON -DCLI11_SINGLE_FILE_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_GENERATOR="Visual Studio 14 2015"
  - ps: cmake --build .
  - cd ..
  - conan create . CLIUtils/CLI11

test_script:
  - cd build
  - ps: ctest --output-on-failure -C Debug

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/0185e91c5d989a476d7b
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
