language: cpp
dist: trusty

# Exclude ghpages,
# but even better, don't build branch and PR, just PR
# Include tags starting with v and a digit
branches:
  only:
  - master
  - /^v\d/

cache:
  apt: true
  directories:
  - "${TRAVIS_BUILD_DIR}/deps/doxygen"

matrix:
  include:
    # Default clang
  - compiler: clang
    script:
    - .ci/make_and_test.sh 11
    - .ci/make_and_test.sh 14
    - .ci/make_and_test.sh 17

    # Docs and clang 3.5
  - compiler: clang
    env:
    - DEPLOY_MAT=yes
    addons:
      apt:
        packages:
        - clang-3.5
    install:
    - export CC=clang-3.5
    - export CXX=clang++-3.5
    script:
    - .ci/make_and_test.sh 11
    after_success:
    - export DOXYFILE=$TRAVIS_BUILD_DIR/docs/Doxyfile
    - export DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - |
      if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]
      then
        . .ci/build_doxygen.sh
        .ci/build_docs.sh
      fi

    # GCC 7 and coverage (8 does not support lcov, wait till 9 and new lcov)
  - compiler: gcc
    env:
    - GCC_VER=7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - curl
        - lcov
    install:
    - export CC=gcc-7
    - export CXX=g++-7
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - cd $TRAVIS_BUILD_DIR
    - ". .ci/build_lcov.sh"
    - ".ci/run_codecov.sh"
    script:
    - .ci/make_and_test.sh 11 -DCLI11_EXAMPLE_JSON=ON
    - .ci/make_and_test.sh 14 -DCLI11_EXAMPLE_JSON=ON
    - .ci/make_and_test.sh 17 -DCLI11_EXAMPLE_JSON=ON

    # GCC 4.7 and Conan
  - compiler: gcc
    env:
    - GCC_VER=4.7
    addons:
      apt:
        packages:
        - g++-4.7
    install:
    - export CC=gcc-4.7
    - export CXX=g++-4.7
    - python -m pip install --user conan
    - conan user
    script:
    - .ci/make_and_test.sh 11
    after_success:
    - conan create . cliutils/stable
    - |
      if [ "${TRAVIS_TAG}" ]
      then
        conan remote add origin https://api.bintray.com/conan/cliutils/CLI11
        conan user -p ${BINFROG_API_KEY} -r origin henryiii
        conan upload "*" -c -r origin --all
      fi

    # GCC 4.8
  - compiler: gcc
    env:
    - GCC_VER=4.8
    addons:
      apt:
        packages:
        - g++-4.8
    install:
    - export CC=gcc-4.8
    - export CXX=g++-4.8
    script:
    - .ci/make_and_test.sh 11

install: skip

script:
- .ci/make_and_test.sh 11
- .ci/make_and_test.sh 14


deploy:
  provider: releases
  api_key:
    secure: L1svZ5J+RiR67dj1fNk/XiZRvYfGJC4c5/dKSvDH+yuKSzZ6ODaTiVmYF8NtMJ7/3AQenEa0OuRBVQ0YpngFz3ugIcRsGCDUHtCMK/Bti0+6ZFdICbqcv6W3BlRIM8s7EOBPhjfbCV+ae7xep9B24HmwBPKukMFjDIj4nwBsmwCHZK9iNFtfaW2J2cr2TJo7QPY01J0W1k/boaj91KzHf9UuhEH8KYqp7szv+6kV00W8bRBtugw419dIm25eXFXgXDT9s/OA7qXV7o5FXWWpkyJ5AINVbY9DerkYag5TStrdOyKk+S1FexRG6TMG4L4Jyu/QxQGhMdu0m1yRCLvIekGtWLDnjNrI2SZrd5HbKprQ0O8j1770Is4q5blVPqAZ6O9jVMJRtVEaYbsJwItz1BJWkPT4S9GFbDL1dq2Z5jR2f5gd/cz2yYH56b47iYHWtzSqEfVhsXiN+atD+tWyQFA4Q/av0bGHwJ6LX0A1q0OCHruUMoxcw1QKfYtV1bkf/folL4Z4Hx3CL+NB0Lkqs8LFsQHxODP4a26I5DS/kaDHofotho8wsWlKFDtonZa+CExORGFFMPnGRz2qX5tMgGoo84wcqrprfoQv2llqeUr3gISPl2qxrljAhj3/Dcl7iI7k0Er7Ji8ENpgjSec4aqnBx8Ke2yaDEmBvwbouFCM=
  skip_cleanup: true
  file: build/include/CLI11.hpp
  on:
    repo: CLIUtils/CLI11
    tags: true
    condition: "$DEPLOY_MAT = yes"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/bbdb3befce4c00448d24
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
  - secure: cY0OI609iTAxLRYuYQnNMi+H6n0dBwioTAoFXGGRTnngw2V9om3UmY5eUu4HQEQsQZovHdYpNhlSgRmdwQ4UqSp3FGyrwobf0kzacV4bVnMDeXDmHt8RzE5wP/LwDd8elNF6RRYjElY99f0k0FyXVd0fIvuVkGKQECNLOtEk0jQo+4YTh7dhuCxRhBYgTbNiRL6UJynfrcK0YN+DQ+8CJNupu2VxgaEpCSngTfvDHLcddcrXwpvn3MPc3FsDUbtN389ZCIe41qqIL0ATv46DQaTw4FOevyVfRyrBOznONoGCVeAYKL6VBdrk01Fh6aytF5zgI3hKaKobgEn+QFfzR6l68c6APvqA0Qv39iLjuh6KbdIV2YsqXfyt6FBgqP2xZuNEZW1jZ8LxUOLl2I40UEh87nFutvnSbfIzN+FcLrajm2H2jV2kZGNKAMx+4qxkZuXSre4JPkENfJm2WNFAKlqPt4ZSEQarkDYzZPcEr2I9fbGjQYVJICoN4LikCv9K5z7ujpTxCTNbVpQWZcEOT6QQBc6Vml/N/NKAIl9o2OeTLiXCmT31+KQMeO492KYNQ6VmkeqrVhGExOUcJdNyDJV9C+3mSekb3Sq78SneYRKDechkWbMl0ol07wGTdBwQQwgaorjRyn07x1rDxpPr3z19/+eubnpPUW4UQ5MYsjs=
  - secure: G6H5HA9pPUgsd96A+uvTxbLjR1rcT9NtxsknIkFDfzGDpffn6wVX+kCIQLf9zFDnQnsfYA/4piiuoBN5U5C7HQrh9UCvBVptXjWviea0Y7CRbMJZpw2rPvXWQtrFNzYkaV7kdJ5B0Mmvh6rcH/I8gKFrkdjF7i7sfzWdFWRU5QXfxXOk2n+xCXX6uFemxHH9850XEjVtnU7YYUebQFaoTYLLy05nlt9JaEF84wfJljY/SJX7I9gpNLtizE9MpJylnrwUeL66OqFievmjL3/bWpPUBjUF0WdtXYlVDja7O582FQDs94ofgqeGieGIMQ0VuovpbQOJSdjs5XHZwu2ce6HZxtOhJJqw6xEwbq43ZdofAlJ5GUEOgrr+j25zIDkdzOhliDKJtw5ysmmTUKEcZ36iWbCE0YP/IC42yOV9oOP6UkgbuwpVDdxAFRgLZLahW9Ok+c1PlzIauPxv+jIEI4rSEEJRKZG2JK3TXUdhd58mHBfQMNjKQMF+Y2wCCGjfMO0q4SgvBhYyb4oBTxEqnc2Pzh2DJdNzRFsV7ktsQSRglHGVI+1XTmQ+2kbBzNOQBLjOuRvDZENUhyxPKGZDHyAOMlVvYm8vvWebM1/F3YgDb/tPh33+EGSvpKkCZ5nUxB5e605H6gdYlNKNhuWKlEKTo2/kF0D39gAUCIcGbzw=
  - CCACHE_CPP2: yes
