language: cpp
sudo: false
branches:
  exclude:
    - gh-pages
env:
  global:
    - secure: "Tdqt9SFIri3bu3B0D1aJqkYr5Zhy1yuBgvL5xC84w96DX45/gq27q51jEHxZdyhAo71D5UNxd9It7aRDMixoYmHj9VvPmhX3o34JKcXsXTFmK6Mks55E8gVr8FJfX7Efl8TSrZ677c51aUeScIaLnpL7G2VoKAqp8GA15foBgggQYjMC6h0ciDRh39GEKUWc/aZa1+uqsTw8rYfDTUn6fQ4GQqVaFhcN14V4vDOleeHM17GgOSoZTPXMi/9qAgRkASARvkdndWYwAIu8XFgu7Za8mWqpn2lpl9Yfv/YbRoPTm8FC9yH4VSbS1YKUw2vS6ehdpgqp8c8ANqoCKp4nUTY6O+5HYJO8bq3pvYOdz2Uz99gSagzIQ/JHxPHQ6GH/3j7e79OWI810FLtG7jJ4SCnBrN8tSCWeDlCatDEMyAchXB2bAns61Tcu5Welf9wLYDgFWYlYl20X6Y/a1B44yczvu8h+McptcNCPola2xLj+TVTc5EewgjAFgpugtx39XMC/GLaY74wv+Q4rX0o1V4AQgZ42fXPKpUeum2JXzBD+Sw0Qzp8cu+qGMjLv2i0BoKcOtQ6LuJsftq/0p/EjnlZCupHeV0aiujNHqB1KkKdTX/aerPNef0Xz3ZL+eukGTwTbFUxng4zkV4JL+3f9RykzJ0TJDMavZSPggXXP4P0="
    - COVERALLS_SERVICE_NAME: travis-ci
    - COVERALLS_REPO_TOKEN: abc12345
cache:
  directories:
  - ${TRAVIS_BUILD_DIR}/deps/cmake
  - ${TRAVIS_BUILD_DIR}/deps/doxygen
matrix:
  include:
  - compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-3.5
        - ubuntu-toolchain-r-test
        packages:
        - clang-3.5
    env:
      - COMPILER=3.5
      - DEPLOY_MAT=yes
      - DOXYFILE=$TRAVIS_BUILD_DIR/docs/Doxyfile
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - lcov
        - curl
    env:
    - COMPILER=6
    - COVERALLS=yes
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.7
    env:
    - COMPILER=4.7
  - os: osx

install:
- python -c 'import sys; print(sys.version_info[:])'
- if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="g++-$COMPILER" CC="gcc-$COMPILER"; fi
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-$COMPILER" CC="clang-$COMPILER"; fi
- if ["$TRAVIS_OS_NAME" = "osx" ] ; then export CXX="clang++" CC="clang"; fi
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- if [ "$TRAVIS_OS_NAME" = "linux" ] ; then cd $TRAVIS_BUILD_DIR && . .ci/build_cmake.sh ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ] ; then cd $TRAVIS_BUILD_DIR && . .ci/build_doxygen.sh ; fi
- cd "${DEPS_DIR}"
- if [ "$(python -c 'import sys; print(sys.version_info[0])')" = "2" ] ; then pip
  install --user pathlib; fi

script:
- cd "${TRAVIS_BUILD_DIR}"
- .ci/travis.sh

after_success:
- echo "${TRAVIS_BRANCH}"
- echo "${TRAVIS_PULL_REQUEST}"
- if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" && "$DEPLOY_MAT" == "yes" ]] ; then echo "Updating docs" &&  cd $TRAVIS_BUILD_DIR && .ci/build_docs.sh ; fi

deploy:
  provider: releases
  api_key:
    secure: bMRTGeFlCmLUJ9EAxCSDPzd5MYGq8Ns2sCr2dCMK/6UL/WeEnwFMkvkBpXvKuG5BHfPft3uttxXI9gtpgTfTym0HCid3QHI5ibl1rKwGXdSx/n++OzZOpwcAgBeM1xSy3qlUSRyZ2zbSgI5KABg4dHezXPRg4S60NFmRNIJtn9zDE847iyGxM7mYtC7aKEZ5KkJAV5MMI8EkicJzBcpREN54NrF8PSw8peCZABIXU27gKvTVf8hxNAwbUzWkUp+YQ693ZA4KGDXIGGN3bngJ2rdxyoLquCEIBDh3Camub+M2PFsKjjHsLRBkVkKXR1BXEJMbROlr9ovlGxL90p7BMZULvVEmGRj2t6ClQdgc8gqyuAaQirr6LpWlXpKjREDgc130ZsEAMY2wTwlaIwjDEIKEyDcEEK4sglCrAg6xQzsNBPMDHYGc6mgbazmvy84UygLl+xXJe2vl/Z875RJBMekBLCKlwgMe+PDO1KGpPOpsLDHwj/Fq3G2+X/WL2ZInaJMhuuvaVJI/AspvEhWWFC6RaoK2q21aTNaDaLFpr0npKKyizcVbdjzEAARL2/sSWka8SWozPCCwDcm2AcunAwnHLylPqZ+Dk2wmrbdztqiALO6GpkMM1ARUIP+laUccVPmCVZeUoTzGLac/QFf6ip+DUG2uQ77q1NjIA6IXCzM=
  skip_cleanup: true
  file: build/include/CLI11.hpp
  on:
    repo: henryiii/CLI11
    tags: true
    condition: $DEPLOY_MAT = yes
